name: BlaBlaBlocks Slider Block Plugin Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up caching for plugin zip
      - name: Cache Plugin Zip
        id: cache-zip
        uses: actions/cache@v3
        with:
          path: plugin.zip
          key: pr-${{ github.event.number }}-${{ github.sha }}

      # Step 3: Create plugin zip if not cached
      - name: Create Plugin Zip
        if: steps.cache-zip.outputs.cache-hit != 'true'
        run: |
          mkdir -p plugin
          rsync -av --progress . plugin --exclude .git --exclude .github
          zip -r plugin.zip plugin
        shell: bash

      # Step 4: Upload or Update Plugin on GitHub Releases
      - name: Upload to GitHub Releases
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "plugin.zip"
          tag: "pr-${{ github.event.number }}"
          release_name: "PR-${{ github.event.number }} Plugin Build"
          body: "Plugin build for PR-${{ github.event.number }}"
          draft: true

      # Step 5: Generate WordPress Playground Link
      - name: Generate Playground Link
        id: generate_link
        run: |
          echo "https://playground.wordpress.net/?plugin=https://github.com/${{ github.repository }}/releases/download/pr-${{ github.event.number }}/plugin.zip" > playground-link.txt

      # Step 6: Post Playground Link as a PR Comment
      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const link = fs.readFileSync('playground-link.txt', 'utf8').trim();
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Test the plugin in WordPress Playground: [Click here](${link})`
            });
