name: Safe Sync dev to testing (with PR fallback)

on:
  push:
    branches:
      - dev

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Check if testing branch exists
        id: check_testing
        run: |
          if git show-ref --verify --quiet refs/remotes/origin/testing; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "::notice::Branch 'testing' does not exist. Skipping merge."
          fi
          
      - name: Attempt merge dev → testing
        id: merge_attempt
        if: steps.check_testing.outputs.exists == 'true'
        run: |
          git checkout testing
          git reset --hard origin/testing
          git clean -fd
          if git merge origin/dev --no-edit; then
            echo "merged=true" >> $GITHUB_OUTPUT
          else
            echo "merged=false" >> $GITHUB_OUTPUT
            echo "::warning::Merge conflict detected. Falling back to PR creation."
            git merge --abort || true
            git reset --hard
            git clean -fd
          fi

      - name: Push changes to testing
        if: steps.merge_attempt.outputs.merged == 'true'
        run: git push origin testing

      - name: Create pull request from dev to testing
        if: steps.merge_attempt.outputs.merged == 'false'
        id: create_pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Sync dev to testing"
          body: "This pull request was automatically generated because an automatic merge from `dev` to `testing` failed."
          base: testing
          head: dev
          draft: false
