name: Safe Sync dev to testing (with PR fallback)

on:
  push:
    branches:
      - dev

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dev
        uses: actions/checkout@v3
        with:
          # Check out dev specifically
          ref: dev
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Clean workspace
        run: |
          # Remove untracked files/directories to avoid leftover artifacts
          git clean -ffd

      - name: Fetch all branches
        run: git fetch --all

      - name: Check if 'testing' branch exists on remote
        id: check_testing
        run: |
          if git ls-remote --exit-code origin testing; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "::notice::Branch 'testing' does not exist. Skipping merge."
          fi

      - name: Checkout testing
        if: steps.check_testing.outputs.exists == 'true'
        run: |
          git checkout -B testing origin/testing

      - name: Attempt merge dev → testing
        id: merge_attempt
        if: steps.check_testing.outputs.exists == 'true'
        run: |
          # Merge dev into testing
          if git merge --no-edit origin/dev; then
            echo "merged=true" >> $GITHUB_OUTPUT
          else
            echo "merged=false" >> $GITHUB_OUTPUT
            echo "::warning::Merge conflict detected. Falling back to PR creation."
            # Abort the merge if conflict occurs
            git merge --abort || true
            # Reset to testing's original state
            git reset --hard origin/testing
            git clean -ffd
          fi

      - name: Push changes to testing
        if: steps.merge_attempt.outputs.merged == 'true'
        run: |
          # Force-push to ensure local merges get reflected on remote
          git push origin HEAD:testing

      - name: Create pull request from dev to testing
        if: steps.merge_attempt.outputs.merged == 'false'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Sync dev to testing"
          body: "This pull request was automatically generated because an automatic merge from `dev` to `testing` failed."
          base: testing
          branch: sync/dev-to-testing
          draft: false
