name: Update Tested Up To

on:
  schedule:
    - cron: "23 6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-tested-up-to:
    uses: lubusIN/.github/.github/workflows/update-tested-up-to.yml@main
    with:
      plugin-slug: blablablocks-slider-block
      release-branch: 1.x
      run-javascript-checks: true
      run-e2e: true
    secrets:
      SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
      SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
